name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    name: Build - Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew assemble --no-daemon -Dorg.gradle.jvmargs=-Xmx6G