name: dependency-submission
on: [push]

permissions:
  contents: write

jobs:
  dependency-submission:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    name: Dependency Submission - Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3